# Generated by Django 4.2 on 2025-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('lob_product', models.CharField(blank=True, max_length=100, null=True, verbose_name='LOB (PRODUCT)')),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('own_damage', models.CharField(blank=True, max_length=50, null=True)),
                ('third_party', models.CharField(blank=True, max_length=50, null=True)),
                ('terrorism_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('booking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_cc', models.IntegerField(blank=True, null=True)),
                ('gvw', models.CharField(blank=True, max_length=100, null=True)),
                ('idv_of_vehicle', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('manufacture_year', models.IntegerField(blank=True, null=True)),
                ('ncb', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('od_brok_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tp_terr_brok_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_grid', models.CharField(blank=True, max_length=100, null=True)),
                ('od_brok_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tp_terr_brok_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agency_comm_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('agency_comm_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deduction_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('less_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tibpl_share', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('csv_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='login_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('mobile', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
