# Generated by Django 4.2 on 2025-05-12 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='entry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
