# Generated by Django 4.2 on 2025-05-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_insurance_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='email_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
