# Generated by Django 4.2 on 2025-05-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_insurance_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data', models.TextField()),
            ],
        ),
    ]
