# Generated by Django 4.2 on 2025-05-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
