# Generated by Django 4.2 on 2025-05-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
