# Generated by Django 4.2 on 2025-05-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_uploadedcsv_delete_uploadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='uploaded_csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='myapp.uploadedcsv'),
        ),
    ]
