# Generated by Django 4.2 on 2025-05-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_insurance_uploaded_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='uploaded_csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='myapp.uploadedcsv'),
        ),
    ]
