# Generated by Django 4.2 on 2025-05-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_insurance_uploaded_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='csv_file',
        ),
    ]
