# Generated by Django 4.2 on 2025-05-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_insurance_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='uploaded_csv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='myapp.uploadedcsv'),
            preserve_default=False,
        ),
    ]
