# Generated by Django 4.2 on 2025-05-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_insurance_uploaded_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='uploaded_csv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadedcsv'),
        ),
    ]
