# Generated by Django 4.2 on 2025-05-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_login_tbl_groups_login_tbl_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_tbl',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
