# Generated by Django 4.2 on 2025-05-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_is_admin_login_tbl_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_tbl',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
