# Generated by Django 4.2 on 2025-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_is_staff_login_tbl_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_tbl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='login_tbl',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='login_tbl',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
