# Generated by Django 4.2 on 2025-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_login_tbl_is_active_alter_login_tbl_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_tbl',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='login_tbl',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='login_tbl',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='login_tbl',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='login_tbl',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login_tbl',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
