# Generated by Django 4.2 on 2025-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_login_tbl_groups_login_tbl_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_tbl',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
