# Generated by Django 4.2 on 2025-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_login_tbl_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_tbl',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
