# Generated by Django 4.2 on 2025-05-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_adduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='block',
            field=models.BooleanField(default=False),
        ),
    ]
