# Generated by Django 4.2 on 2025-05-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_adduser_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adduser',
        ),
        migrations.AddField(
            model_name='login_tbl',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login_tbl',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
