# Generated by Django 4.2 on 2025-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='unlimited',
        ),
        migrations.AlterField(
            model_name='permission',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
